Repository cbnu-sequence/proreviewer-web-front, pull requests merged in 2022-09, with the labels that each got.

#3 Feat: 사이드바 drag, open, close 기능 추가
  common/components/Header/index.tsx
  common/components/Header/styles.tsx
  components/Home/index.tsx
  components/Home/styles.tsx
  package-lock.json
  package.json
  pages/index.tsx
  state/recoil/recoilKeys/index.ts
  yarn.lock
Labels: feat, fix

#14 Design: 로고 제작 및 헤더 UI 수정
  components/common/Header/index.tsx
  components/common/Header/styles.tsx
  package-lock.json
  public/proReLogo.png
Labels: design

#18 [OAUTH] 인증에 관련된 hook을 만들어 추상화하며 깃허브 인증을 만들었습니다. (#4)
  .eslintrc.json
  apis/auth.ts
  components/Login/Social.tsx
  components/Login/index.tsx
  constants/login.ts
  docs/auth.md
  package-lock.json
  package.json
  pages/redirect/index.tsx
  state/react-query/hooks/auth.ts
  state/recoil/user.ts
  tsconfig.json
  types/type.ts
  user-storage/index.ts
  yarn.lock
Labels: review request, documentation, feat

#20 [Main] dev브랜치 최종 확인 후 main브랜치로 병합
  .eslintrc.json
  README.md
  apis/auth.ts
  common/hooks/useCustomToast.ts
  components/Calendar/index.tsx
  components/Home/index.tsx
  components/Home/styles.tsx
  components/Login/Social/index.tsx
  components/Login/index.tsx
  components/Login/styles.tsx
  components/Redirect/index.tsx
  components/common/Footer/index.tsx
  components/common/Header/index.tsx
  components/common/Header/styles.tsx
  components/common/Loading/index.tsx
  components/common/Loading/styles.tsx
  components/common/Toast/ToastItem/index.tsx
  components/common/Toast/ToastItem/styles.tsx
  components/common/Toast/index.tsx
  components/common/Toast/styles.tsx
  constants/login.ts
  cookie/user-storage.ts
  cypress.config.ts
  docs/auth.md
  hooks/test/useInput.test.js
  hooks/useInput.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/calendar/index.tsx
  pages/index.tsx
  pages/redirect/index.tsx
  public/proReLogo.png
  state/react-query/hooks/auth.ts
  state/react-query/hooks/types/auth.ts
  state/recoil/recoilKeys/index.ts
  state/recoil/toastList.ts
  state/recoil/user.ts
  styles/colors.ts
  styles/globals.css
  test/cypress/e2e/login.cy.ts
  test/jest/home/index.test.js
  tsconfig.json
  yarn.lock
Labels: documentation, feat, design, refactor, chore, main
